require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*' 
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - "**/spec/**/*"
    - 'app/mailers/*'

Layout/LineLength:
    Max: 176

Metrics/MethodLength:
    Max: 20

Metrics/AbcSize:
    Max: 35

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 200

Metric/MethodLength:
  Max: 200

Layout/LineLength:
  Max: 275

Metrics/ClassLength:
  Max: 120